### ISSUE TITLE
ImportError when trying to import WKTPlot

### ISSUE THREAD

**Issue by grndng** [FuzzFoundation/WKTPlot#15]
Hey there,

I'm getting the following error message when I try to import WKTPlot for the first time after installation with `pip install wktplot`:

```python
ImportError: cannot import name 'WKTPlot' from 'wktplot' (C:\Users\<username>\AppData\Roaming\Python\Python310\site-packages\wktplot\__init__.py)
```

I don't exactly know what the problem is. Although I'm able to import `wktplot`, I am not able to import `WKTPlot`. I'm also not able to use `wktplot.WKTPlot` which throws following error message:

```python
plot = wktplot.WKTPlot(title="title", save_dir="/plots")
AttributeError: module 'wktplot' has no attribute 'WKTPlot'
```

When I copy the WKTPlot file from your source (https://github.com/FuzzFoundation/WKTPlot/blob/main/src/wktplot/wktplot.py) and create a local *.py file to import from, it works as supposedly intended.

In case versioning might cause an issue:
* Python version: 3.10.2
* Shapely version: 1.8.0
* wktplot version: 1.0.1
* Bokeh version: 2.4.2
* Jinja2 version: 3.0.3

**Comment by misimpso** [comment]
Thanks for the issue. We're still trying to iron out our new github actions for building and publishing the package to pypi after the refactor https://github.com/FuzzFoundation/WKTPlot/pull/9.

The old way of importing which will work with the version on PyPI is:
``` python
from wktplot.wkt_plot import WKTPlot
```

The refactor just simplified the package structure and moved towards using Github actions instead of CircleCI. I will be working on getting the building and publishing working hopefully soon.

**Comment by grndng** [comment]
I can confirm that the workaround works - thanks! :)

**Comment by misimpso** [comment]
This is now fixed. Version 2.0.0 is now available on PyPi. https://pypi.org/project/wktplot/2.0.0/
